spring:
  application:
    name: pizza-service
  datasource:
    url: jdbc:postgresql://localhost:5432/pizza
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
  webflux:
    reactor:
      netty:
        tcp:
          max-threads: 1024
