version: "3.9"
services:
  app1:
    image: pr5
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      - NAME_APP=app1
    volumes:
      - ../storage:/storage

  app2:
    image: pr5
    restart: on-failure
    environment:
      - NAME_APP=app2
    volumes:
      - ../storage:/storage

  app3:
    image: pr5
    restart: on-failure
    environment:
      - NAME_APP=app3
    volumes:
      - ../storage:/storage

  app4:
    image: pr5
    restart: on-failure
    environment:
      - NAME_APP=app4
    volumes:
      - ../storage:/storage

  proxy:
    image: nginx:1.11
    ports:
      - '85:85'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
